a = input('Digite algo:')
print('O tipo primitivo dessa entrada é:', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está tudo em maiúscula?', a.isupper())
print('Está tudo em minúscula?', a.islower())
print('Está capitalizada?', a.istitle())
